"""remove test field

Revision ID: 4efab9d4cdb8
Revises: 786e412c6731
Create Date: 2025-11-05 21:05:32.485426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efab9d4cdb8'
down_revision = '786e412c6731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
