"""add test field

Revision ID: 786e412c6731
Revises: 
Create Date: 2025-11-05 21:05:19.354071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786e412c6731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
