"""Add read write flags to user file permissions

Revision ID: e00ee851dca5
Revises: 4efab9d4cdb8
Create Date: 2025-11-07 12:59:33.915987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00ee851dca5'
down_revision = '4efab9d4cdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_file_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_read', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_write', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_column('permission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_file_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('can_write')
        batch_op.drop_column('can_read')

    # ### end Alembic commands ###
